---
abstract: 'Creates Catalyst components from config entries'
author:
  - 'Peter Flanigan <pjfl@cpan.org>'
build_requires:
  Module::Build: 0.4004
  Test::More: 0.74
  version: 0.88
configure_requires:
  Module::Build: 0.4004
  version: 0.88
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300033, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-ConfigComponents
requires:
  Catalyst: 5.90010
  Devel::InnerPackage: 0.3
  MRO::Compat: 0.11
  Module::Pluggable: 4.8
  Moose: 2.0402
  Path::Class: 0.16
  namespace::autoclean: 0.05
  parent: 0.224
  version: 0.88
version: 0.7.1
